package com.codeHustlers.OpenInnovation.Model;

//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
import lombok.Getter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Document(collection = "companies")
public class Company {

    // Getters and Setters
    @Getter
    @Id
    private String companyId; // Autogenerated by MongoDB
    private String name;
    private String description;
    private String domain;

    private String type;
    private String password;
    @DBRef
    private List<Challenge> challenges;


    // Constructors
    public Company() {}

    public Company(String name, String description) {
        this.name = name;
        this.description = description;
    }


    public String getDomain() {
        return domain;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
